#include <iostream>

using namespace std;

void picas(int n){
    switch(n){
    case 1: cout<<" _____"<<endl;
            cout<<"|A .  |"<<endl;
            cout<<"| /.\\ |"<<endl;
            cout<<"|(_._)|"<<endl;
            cout<<"|  |  |"<<endl;
            cout<<"|____V|"<<endl;
        break;
    case 2: cout<<" _____"<<endl;
            cout<<"|2    |"<<endl;
            cout<<"|  ^  |"<<endl;
            cout<<"|     |"<<endl;
            cout<<"|  ^  |"<<endl;
            cout<<"|____Z|"<<endl;
        break;
    case 3: cout<<" _____"<<endl;
            cout<<"|3    |"<<endl;
            cout<<"| ^ ^ |"<<endl;
            cout<<"|     |"<<endl;
            cout<<"|  ^  |"<<endl;
            cout<<"|____E|"<<endl;
        break;
    case 4: cout<<" _____"<<endl;
            cout<<"|4    |"<<endl;
            cout<<"| ^ ^ |"<<endl;
            cout<<"|     |"<<endl;
            cout<<"| ^ ^ |"<<endl;
            cout<<"|____h|"<<endl;
        break;
    case 5: cout<<" _____"<<endl;
            cout<<"|5    |"<<endl;
            cout<<"| ^ ^ |"<<endl;
            cout<<"|  ^  |"<<endl;
            cout<<"| ^ ^ |"<<endl;
            cout<<"|____S|"<<endl;
        break;
    case 6: cout<<" _____"<<endl;
            cout<<"|6    |"<<endl;
            cout<<"| ^ ^ |"<<endl;
            cout<<"| ^ ^ |"<<endl;
            cout<<"| ^ ^ |"<<endl;
            cout<<"|____9|"<<endl;
        break;
    case 7: cout<<" _____"<<endl;
            cout<<"|7    |"<<endl;
            cout<<"| ^ ^ |"<<endl;
            cout<<"|^ ^ ^|"<<endl;
            cout<<"| ^ ^ |"<<endl;
            cout<<"|____L|"<<endl;
        break;
    case 8: cout<<" _____"<<endl;
            cout<<"|8    |"<<endl;
            cout<<"|^ ^ ^|"<<endl;
            cout<<"| ^ ^ |"<<endl;
            cout<<"|^ ^ ^|"<<endl;
            cout<<"|____8|"<<endl;
        break;
    case 9: cout<<" _____"<<endl;
            cout<<"|9    |"<<endl;
            cout<<"|^ ^ ^|"<<endl;
            cout<<"|^ ^ ^|"<<endl;
            cout<<"|^ ^ ^|"<<endl;
            cout<<"|____6|"<<endl;
        break;
    case 10:cout<<" _____"<<endl;
            cout<<"|10 ^ |"<<endl;
            cout<<"|^ ^ ^|"<<endl;
            cout<<"|^ ^ ^|"<<endl;
            cout<<"|^ ^ ^|"<<endl;
            cout<<"|___0I|"<<endl;
        break;
    case 11:cout<<" _____"<<endl;
            cout<<"|J  ww|"<<endl;
            cout<<"| ^ {)|"<<endl;
            cout<<"|(.)% |"<<endl;
            cout<<"| | % |"<<endl;
            cout<<"|__%%[|"<<endl;
        break;
    case 12:cout<<" _____"<<endl;
            cout<<"|Q  ww|"<<endl;
            cout<<"| ^ {(|"<<endl;
            cout<<"|(.)%%|"<<endl;
            cout<<"| |%%%|"<<endl;
            cout<<"|_%%%O|"<<endl;
        break;
    case 13:cout<<" _____"<<endl;
            cout<<"|K  WW|"<<endl;
            cout<<"| ^ {)|"<<endl;
            cout<<"|(.)%%|"<<endl;
            cout<<"| |%%%|"<<endl;
            cout<<"|_%%%>|"<<endl;
        break;
    }
}

void trebol(int n){
    switch(n){
    case 1: cout<<" _____"<<endl;
            cout<<"|A _  |"<<endl;
            cout<<"| ( ) |"<<endl;
            cout<<"|(_'_)|"<<endl;
            cout<<"|  |  |"<<endl;
            cout<<"|____V|"<<endl;
        break;
    case 2: cout<<" _____"<<endl;
            cout<<"|2    |"<<endl;
            cout<<"|  &  |"<<endl;
            cout<<"|     |"<<endl;
            cout<<"|  &  |"<<endl;
            cout<<"|____Z|"<<endl;
        break;
    case 3: cout<<" _____"<<endl;
            cout<<"|3    |"<<endl;
            cout<<"| & & |"<<endl;
            cout<<"|     |"<<endl;
            cout<<"|  &  |"<<endl;
            cout<<"|____E|"<<endl;
        break;
    case 4: cout<<" _____"<<endl;
            cout<<"|4    |"<<endl;
            cout<<"| & & |"<<endl;
            cout<<"|     |"<<endl;
            cout<<"| & & |"<<endl;
            cout<<"|____h|"<<endl;
        break;
    case 5: cout<<" _____"<<endl;
            cout<<"|5    |"<<endl;
            cout<<"| & & |"<<endl;
            cout<<"|  &  |"<<endl;
            cout<<"| & & |"<<endl;
            cout<<"|____S|"<<endl;
        break;
    case 6: cout<<" _____"<<endl;
            cout<<"|6    |"<<endl;
            cout<<"| & & |"<<endl;
            cout<<"| & & |"<<endl;
            cout<<"| & & |"<<endl;
            cout<<"|____9|"<<endl;
        break;
    case 7: cout<<" _____"<<endl;
            cout<<"|7    |"<<endl;
            cout<<"| & & |"<<endl;
            cout<<"|& & &|"<<endl;
            cout<<"| & & |"<<endl;
            cout<<"|____L|"<<endl;
        break;
    case 8: cout<<" _____"<<endl;
            cout<<"|8    |"<<endl;
            cout<<"|& & &|"<<endl;
            cout<<"| & & |"<<endl;
            cout<<"|& & &|"<<endl;
            cout<<"|____8|"<<endl;
        break;
    case 9: cout<<" _____"<<endl;
            cout<<"|9    |"<<endl;
            cout<<"|& & &|"<<endl;
            cout<<"|& & &|"<<endl;
            cout<<"|& & &|"<<endl;
            cout<<"|____6|"<<endl;
        break;
    case 10:cout<<" _____"<<endl;
            cout<<"|10 & |"<<endl;
            cout<<"|& & &|"<<endl;
            cout<<"|& & &|"<<endl;
            cout<<"|& & &|"<<endl;
            cout<<"|___0I|"<<endl;
        break;
    case 11:cout<<" _____"<<endl;
            cout<<"|J  ww|"<<endl;
            cout<<"| 0 {)|"<<endl;
            cout<<"|0 0% |"<<endl;
            cout<<"| | % |"<<endl;
            cout<<"|__%%[|"<<endl;
        break;
    case 12:cout<<" _____"<<endl;
            cout<<"|Q  ww|"<<endl;
            cout<<"| 0 {(|"<<endl;
            cout<<"|0 0%%|"<<endl;
            cout<<"| |%%%|"<<endl;
            cout<<"|_%%%O|"<<endl;
        break;
    case 13:cout<<" _____"<<endl;
            cout<<"|K  WW|"<<endl;
            cout<<"| 0 {)|"<<endl;
            cout<<"|0 0%%|"<<endl;
            cout<<"| |%%%|"<<endl;
            cout<<"|_%%%>|"<<endl;
        break;
    }
}

void corazon(int n){
    switch(n){
    case 1: cout<<" _____"<<endl;
            cout<<"|A_ _ |"<<endl;
            cout<<"|( v )|"<<endl;
            cout<<"| \\ / |"<<endl;
            cout<<"|  .  |"<<endl;
            cout<<"|____V|"<<endl;
        break;
    case 2: cout<<" _____"<<endl;
            cout<<"|2    |"<<endl;
            cout<<"|  v  |"<<endl;
            cout<<"|     |"<<endl;
            cout<<"|  v  |"<<endl;
            cout<<"|____Z|"<<endl;
        break;
    case 3: cout<<" _____"<<endl;
            cout<<"|3    |"<<endl;
            cout<<"| v v |"<<endl;
            cout<<"|     |"<<endl;
            cout<<"|  v  |"<<endl;
            cout<<"|____E|"<<endl;
        break;
    case 4: cout<<" _____"<<endl;
            cout<<"|4    |"<<endl;
            cout<<"| v v |"<<endl;
            cout<<"|     |"<<endl;
            cout<<"| v v |"<<endl;
            cout<<"|____h|"<<endl;
        break;
    case 5: cout<<" _____"<<endl;
            cout<<"|5    |"<<endl;
            cout<<"| v v |"<<endl;
            cout<<"|  v  |"<<endl;
            cout<<"| v v |"<<endl;
            cout<<"|____S|"<<endl;
        break;
    case 6: cout<<" _____"<<endl;
            cout<<"|6    |"<<endl;
            cout<<"| v v |"<<endl;
            cout<<"| v v |"<<endl;
            cout<<"| v v |"<<endl;
            cout<<"|____9|"<<endl;
        break;
    case 7: cout<<" _____"<<endl;
            cout<<"|7    |"<<endl;
            cout<<"| v v |"<<endl;
            cout<<"|v v v|"<<endl;
            cout<<"| v v |"<<endl;
            cout<<"|____L|"<<endl;
        break;
    case 8: cout<<" _____"<<endl;
            cout<<"|8    |"<<endl;
            cout<<"|v v v|"<<endl;
            cout<<"| v v |"<<endl;
            cout<<"|v v v|"<<endl;
            cout<<"|____8|"<<endl;
        break;
    case 9: cout<<" _____"<<endl;
            cout<<"|9    |"<<endl;
            cout<<"|v v v|"<<endl;
            cout<<"|v v v|"<<endl;
            cout<<"|v v v|"<<endl;
            cout<<"|____6|"<<endl;
        break;
    case 10:cout<<" _____"<<endl;
            cout<<"|10 v |"<<endl;
            cout<<"|v v v|"<<endl;
            cout<<"|v v v|"<<endl;
            cout<<"|v v v|"<<endl;
            cout<<"|___0I|"<<endl;
        break;
    case 11:cout<<" _____"<<endl;
            cout<<"|J  ww|"<<endl;
            cout<<"|   {)|"<<endl;
            cout<<"|(v)% |"<<endl;
            cout<<"| v % |"<<endl;
            cout<<"|__%%[|"<<endl;
        break;
    case 12:cout<<" _____"<<endl;
            cout<<"|Q  ww|"<<endl;
            cout<<"|   {(|"<<endl;
            cout<<"|(v)%%|"<<endl;
            cout<<"| v%%%|"<<endl;
            cout<<"|_%%%O|"<<endl;
        break;
    case 13:cout<<" _____"<<endl;
            cout<<"|K  WW|"<<endl;
            cout<<"|   {)|"<<endl;
            cout<<"|(v)%%|"<<endl;
            cout<<"| v%%%|"<<endl;
            cout<<"|_%%%>|"<<endl;
        break;
    }
}

void diamante(int n){
    switch(n){
    case 1: cout<<" _____"<<endl;
            cout<<"|A ^  |"<<endl;
            cout<<"| / \\ |"<<endl;
            cout<<"| \\ / |"<<endl;
            cout<<"|  v  |"<<endl;
            cout<<"|____V|"<<endl;
        break;
    case 2: cout<<" _____"<<endl;
            cout<<"|2    |"<<endl;
            cout<<"|  o  |"<<endl;
            cout<<"|     |"<<endl;
            cout<<"|  o  |"<<endl;
            cout<<"|____Z|"<<endl;
        break;
    case 3: cout<<" _____"<<endl;
            cout<<"|3    |"<<endl;
            cout<<"| o o |"<<endl;
            cout<<"|     |"<<endl;
            cout<<"|  o  |"<<endl;
            cout<<"|____E|"<<endl;
        break;
    case 4: cout<<" _____"<<endl;
            cout<<"|4    |"<<endl;
            cout<<"| o o |"<<endl;
            cout<<"|     |"<<endl;
            cout<<"| o o |"<<endl;
            cout<<"|____h|"<<endl;
        break;
    case 5: cout<<" _____"<<endl;
            cout<<"|5    |"<<endl;
            cout<<"| o o |"<<endl;
            cout<<"|  o  |"<<endl;
            cout<<"| o o |"<<endl;
            cout<<"|____S|"<<endl;
        break;
    case 6: cout<<" _____"<<endl;
            cout<<"|6    |"<<endl;
            cout<<"| o o |"<<endl;
            cout<<"| o o |"<<endl;
            cout<<"| o o |"<<endl;
            cout<<"|____9|"<<endl;
        break;
    case 7: cout<<" _____"<<endl;
            cout<<"|7    |"<<endl;
            cout<<"| o o |"<<endl;
            cout<<"|o o o|"<<endl;
            cout<<"| o o |"<<endl;
            cout<<"|____L|"<<endl;
        break;
    case 8: cout<<" _____"<<endl;
            cout<<"|8    |"<<endl;
            cout<<"|o o o|"<<endl;
            cout<<"| o o |"<<endl;
            cout<<"|o o o|"<<endl;
            cout<<"|____8|"<<endl;
        break;
    case 9: cout<<" _____"<<endl;
            cout<<"|9    |"<<endl;
            cout<<"|o o o|"<<endl;
            cout<<"|o o o|"<<endl;
            cout<<"|o o o|"<<endl;
            cout<<"|____6|"<<endl;
        break;
    case 10:cout<<" _____"<<endl;
            cout<<"|10 o |"<<endl;
            cout<<"|o o o|"<<endl;
            cout<<"|o o o|"<<endl;
            cout<<"|o o o|"<<endl;
            cout<<"|___0I|"<<endl;
        break;
    case 11:cout<<" _____"<<endl;
            cout<<"|J  ww|"<<endl;
            cout<<"| /\\{)|"<<endl;
            cout<<"| \\/% |"<<endl;
            cout<<"|   % |"<<endl;
            cout<<"|__%%[|"<<endl;
        break;
    case 12:cout<<" _____"<<endl;
            cout<<"|Q  ww|"<<endl;
            cout<<"| /\\{(|"<<endl;
            cout<<"| \\/%%|"<<endl;
            cout<<"|  %%%|"<<endl;
            cout<<"|_%%%O|"<<endl;
        break;
    case 13:cout<<" _____"<<endl;
            cout<<"|K  WW|"<<endl;
            cout<<"| /\\{)|"<<endl;
            cout<<"| \\/%%|"<<endl;
            cout<<"|  %%%|"<<endl;
            cout<<"|_%%%>|"<<endl;
        break;
    }
}

void asciicard(int n, int palo){

    switch(palo){
        case 1:  picas(n); break;
        case 2:  trebol(n); break;
        case 3:  corazon(n); break;
        case 4:  diamante(n); break;
    }

}
